from constructs import Construct
from aws_cdk import (
    Stack,
    aws_eventschemas as schemas,

)


class TheBusStack(Stack):

    def __init__(self, scope: Construct, construct_id: str, props: dict, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        namespace = props['namespace']

        registry_name = f"{namespace}SchemaRegistry"
        schemas.CfnRegistry(scope=self,
                            id=registry_name,
                            registry_name=registry_name,
                            description="Schema registry for the UMCCR Data Portal Event Bus")

        # TODO: investigate use of custom event schema
        # According to the API (https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_PutEvents.html)
        # events have to be wrapped into a defined AWSEvent format, with arbitrarily definable "Detail" (payload)
        # However, the event bus registry allows events to be defined and schemas created that do not follow that
        # convention. It is unclear how to consolidate those...
        # Also: import of autogenerated classes has its challenges:
        #       - how to pull
        #       - how to reference/build a lambda layer
        #       - objects are not JSON serializable and the use of Marshallers presents extra hurdles
        schemas.CfnSchema(scope=self,
                          id=f"{namespace}FooSchema",
                          schema_name=f"{namespace}FooSchema",
                          description="Schema representing a Foo event",
                          registry_name=registry_name,
                          content="")