# S3 bucket for billing data
resource "aws_s3_bucket" "billing_export" {
  bucket = "billing-export-all-${data.aws_caller_identity.current.account_id}-${data.aws_region.current.id}"
}

# resource "aws_s3_bucket_ownership_controls" "billing_export" {
#   bucket = aws_s3_bucket.billing_export.id
#
#   rule {
#     object_ownership = "BucketOwnerEnforced"
#   }
# }
#
# resource "aws_s3_bucket_public_access_block" "billing_export" {
#   bucket = aws_s3_bucket.billing_export.id
#
#   block_public_acls       = true
#   block_public_policy     = true
#   ignore_public_acls      = true
#   restrict_public_buckets = true
# }

# Bucket policy for AWS Billing service
resource "aws_s3_bucket_policy" "billing_export" {
  bucket = aws_s3_bucket.billing_export.id

  # note that this policy matches the one that was autogenerated by the AWS Console
  # when creating billing exports manually (as at Feb 2026)
  # (someone can always make a new fake report with bucket to confirm that the definition
  #  is still best practice)
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid    = "EnableAWSDataExportsToWriteToS3AndCheckPolicy"
        Effect = "Allow"
        Principal = {
          Service = [
            "billingreports.amazonaws.com",
            "bcm-data-exports.amazonaws.com"
          ]
        }
        Action = [
          "s3:PutObject",
          "s3:GetBucketPolicy"
        ]
        Resource = [
          aws_s3_bucket.billing_export.arn,
          "${aws_s3_bucket.billing_export.arn}/*"
        ],
        Condition = {
          StringLike = {
            "aws:SourceAccount" = data.aws_caller_identity.current.account_id
            "aws:SourceArn" = [
              "arn:aws:cur:us-east-1:${data.aws_caller_identity.current.account_id}:definition/*",
              "arn:aws:bcm-data-exports:us-east-1:${data.aws_caller_identity.current.account_id}:export/*"
            ]
          }
        }
      }
    ]
  })
}
