# S3 bucket for billing data
# noting we are relying on the (as of 2026) AWS defaults which will give us
# - aws encryption
# - blocking public access
# - bucket owner enforced ownership
resource "aws_s3_bucket" "billing_export" {
  bucket = "billing-export-all-${data.aws_caller_identity.current.account_id}-${data.aws_region.current.id}"
}

resource "aws_s3_bucket_policy" "billing_export" {
  bucket = aws_s3_bucket.billing_export.id

  # note that this policy matches the one that was autogenerated by the AWS Console
  # when creating billing exports manually (as at Feb 2026)
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid    = "EnableAWSDataExportsToWriteToS3AndCheckPolicy"
        Effect = "Allow"
        Principal = {
          Service = [
            "billingreports.amazonaws.com",
            "bcm-data-exports.amazonaws.com"
          ]
        }
        Action = [
          "s3:PutObject",
          "s3:GetBucketPolicy"
        ]
        Resource = [
          aws_s3_bucket.billing_export.arn,
          "${aws_s3_bucket.billing_export.arn}/*"
        ],
        Condition = {
          StringLike = {
            "aws:SourceAccount" = data.aws_caller_identity.current.account_id
            "aws:SourceArn" = [
              "arn:aws:cur:us-east-1:${data.aws_caller_identity.current.account_id}:definition/*",
              "arn:aws:bcm-data-exports:us-east-1:${data.aws_caller_identity.current.account_id}:export/*"
            ]
          }
        }
      }
    ]
  })
}
