#!/bin/bash

# wrapper script around 'assume-role' to add env var for Vault access

MAX_TTL='12h'
RENEWAL_PERIOD='12h'

after_script(){

  # build the Vault server address based on the AWS account name
  if [ ! $AWS_ACCOUNT_NAME = "" ]; then
    echo "Using AWS account: $AWS_ACCOUNT_NAME"
  else
    echo "Could not find AWS account name. Make sure AWS_ACCOUNT_NAME is set."
    return
  fi

  export VAULT_ADDR="https://vault.$AWS_ACCOUNT_NAME.umccr.org:8200"

  echo "Removing existing (probably stale) Vault token"
  unset VAULT_TOKEN

  # if GITHUB_TOKEN is not set, the vault login will ask for it
  echo "Attempting a Vault login"
  vault login -method=github token=$GITHUB_TOKEN
  if [ $? != 0 ]; then
    echo "ERROR logging into Vault."
    return
  fi

  echo "Requesting Vault access token..."
    vault_token=$(vault token create -explicit-max-ttl=$MAX_TTL -period=$RENEWAL_PERIOD --format=json | jq -r .auth.client_token)
  echo "$vault_token"
  if [ $vault_token = "" ]; then
    echo "ERROR requesting Vault token"
  fi
  export VAULT_TOKEN="$vault_token"
  echo "Vault access token successful retrieved. Session envars exported."
}



assume-role "$@"
after_script
